version: '3.8'

services:
  the-dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    container_name: the-app
    volumes:
      - .:/app
      - /app/node_modules
